version: "3"
services:
  bootcamp-mongodb:
    image: mongo:latest
    container_name: "bootcamp-mongodb"
    ports:
    - 27017:27017
  config-service:
    image: config-service
    container_name: config-service
    ports:
      - 8090:8090
  eureka-service:
    image: eureka-service
    container_name: eureka-service
    ports:
    - 8099:8099
    links:
      - config-service
  customer-service:
    image: customer-service
    container_name: customer-service
    ports:
      - 8082:8082
    links:
      - bootcamp-mongodb
      - eureka-service
  account-service:
     image: account-service
     container_name: account-service
     ports:
      - 8083:8083
     links:
      - bootcamp-mongodb
      - eureka-service