server:
  port: 8082
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bootcamp-mongodb
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

