server:
  port: 8082
spring:
  data:
    mongodb:
      host: 192.168.0.110
      port: 27017
      database: bootcamp-mongodb
      username: admin
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.110:8099/eureka


