server:
  port: 8082
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bootcamp-mongodb
      username: admin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761

