spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/bootcamp-mongodb
  application:
    name: customer
  cloud:
    config:
      uri: http://localhost:8081
      username: root
      password: p1w1ll0
  boot:
    admin:
      client:
        url: http://localhost:8086
