server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customers/**
          filters:
            - RewritePath=/customer/(?.*), /$\{path}
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/accounts/**
          filters:
            - RewritePath=/account/(?.*), /$\{path}
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/transactions/**
        - id: credit-service
          uri: lb://credit-service
          predicates:
            - Path=/credits/**
        - id: bank-service
            uri: lb://bank-service
            predicates:
              - Path=/banks/**
        - id: atm-service
            uri: lb://atm-service
            predicates:
              - Path=/atm/**
