server:
  port: 8084
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bootcamp-mongodb
      username: admin
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka